server:
  port: 8080
  servlet:
    context-path: /aichat

spring:
  datasource:
    username: root
    password: Gsa123456
    url: jdbc:mysql://localhost:3306/chatdemo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/


mybatis:
  #config-location: classpath:mapper/MyBatisConfig.xml
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.ai.chat.pojo
  #控制台打印mybatis执行的sql语句
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl






